### PR TITLE
Enhancements: Remove duplicate events and show events calendar title.

### PR DESCRIPTION
**Pull request by linsomniac**
I've updated this pull request to include a bunch of changes I've made.  The ultimate goal is to deal with lots of shared calendars better.  When I first pulled up the calendar after running gnome-shell-google-calendar, it took up most of the height on my 30" monitor, because of several events that my whole company is attending, and I am subscribed to everyone's calendars.

Here is an overview of the major changes:
- Only show one event for multiple events with the same title and start date.
- Show which calendar(s) the event is coming from.

Then there are a number of changes that I made as I was wrapping my head around what was happening in this code, to simplify things:
- Make it so that you can enable/disable debugging prints via a global "debug" flag rather than commenting out lines.
- Getting rid of some superfluous "_" variables and backslashes.
- Adding some test code, largely so I could refactor get_month_key without breaking it.
- Refactoring get_month_key() and need_update_near() to be more obvious.  The latter I re-factored once and then re-factored again, hence the two commits.
- Months now store the full event, and events store the calendar title (moving towards the deduplication and calendar display features).

### CODE REVIEW

**Comment by linsomniac** [comment]
Can I get some feedback on why you reverted the "show which calendar event came from"?  If you only have one calendar and don't like seeing it, I could make it auto-hide if you only have one calendar.  I could also make it a command-line option.  Thoughts?

**Comment by vintitres** [comment]
It caused such error:
...
 #Returning 113 events...
process 16559: Array or variant type requires that type string be
written, but end_struct was written.
The overall signature expected here was 'a(sssbxxa{sv})' and we are on
byte 3 of that signature.
  D-Bus not built with -rdynamic so unable to print a backtrace

**Comment by linsomniac** [comment]
Cool, thanks for the feedback.  I'm not exactly sure what is happening, because that version has been running for me for 12 hours without any problems, but I have a plan of attack...

I've pushed up a new version that includes a decorator that will log tracebacks and I've wrapped a few likely candidates.  Can you please try that version and let me know if there are any tracebacks reported?  Also, if you set "debug = True" it will write out function calls and returns -- a lot of data, but maybe something useful will be in there, but it may also contain sensitive information.

If you get a traceback, please send it on my way and I'll take a look at it.

Thanks,
Sean

**Comment by vintitres** [comment]
fixed

**Pull request merged**
